Remove temp profile dir on close
ClimenteA/flaskwebgui pull request #154
Opened 2024-07-08 21:37 UTC by pawrequest

i cleared out my windows temp dir (appdata/local) a week ago, and today i found ~500 FlaskWebGui dirs, 200k subdirs, ~300k files totalling 30gb. 

so i added a TEMP_DIRS_CREATED global list and cleanup_temp_dirs() function. i append profile dir link to the list when it's defined, then call cleanup_temp_dirs() just before kill_port() on exit

2024-07-08 21:46 UTC, pawrequest commented
i think my ruff profile has made some minor spurious formatting edits, feel free to run your own formatter...

2024-07-09 07:42 UTC, ClimenteA requested changes

2024-07-09 07:42 UTC, ClimenteA commented on src/flaskwebgui.py
> +
No need for list and the cleanup_temp_dirs. 
On each app startup only 1 profile dir for the browser is created in tmp folder.

delete them

2024-07-09 07:42 UTC, ClimenteA commented on src/flaskwebgui.py
> +            cleanup_temp_dirs()
Replace `cleanup_temp_dirs()` func with `shutil.rmtree(self.profile_dir, ignore_errors=True)`

2024-07-09 07:42 UTC, ClimenteA commented on src/flaskwebgui.py
> +            cleanup_temp_dirs()
Same here:
Replace `cleanup_temp_dirs()` func with `shutil.rmtree(self.profile_dir, ignore_errors=True)`

Make sure to bump version in setup.py file

2024-07-12 18:40 UTC, ClimenteA approved these changes

2024-07-12 18:41 UTC, merged